version: 2
jobs:
  build:
    branches:
      only:
        - thomSource
        - thomTarget
    docker:
      - image: circleci/node:8.9.4
    environment:
      # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
      # and https://developer.salesforce.com/media/salesforce-cli/manifest.json

      # Variables used in build steps
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      - TESTLEVEL: NoTestRun
    steps:
      - checkout
      - run:
          name: "Configure Salesforce CLI"
          command: |
            # Create sfdx directory
            mkdir sfdx
            # Download cli
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
            # Install the cli
            sudo ./sfdx/install
            sfdx
      - run:
          name: Decrypt Server Key
          command: |
            # Decrypt Server Key
            openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
      - run:
          name: Run Script - Authorize and Deploy to Target Deployment Org
          command: |
            # Run script stored in repository
            ./scripts/deploy.sh

